version: '3'

services:
  fastapi:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  streamlit:
    build: .
    command: streamlit run Home.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - fastapi

  jupyter:
    build: .
    command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser
    ports:
      - "8888:8888"
    volumes:
      - .:/app
